# Google App Engine configuration for qzWhatNext

runtime: python39

env_variables:
  # These should be set in App Engine environment variables or Secret Manager
  # TODOIST_API_TOKEN: your_token_here
  # GOOGLE_CALENDAR_CREDENTIALS_PATH: credentials.json
  # GOOGLE_CALENDAR_ID: primary
  DEBUG: "False"

handlers:
- url: /.*
  script: auto

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

