# Google App Engine configuration for qzWhatNext

runtime: python39

env_variables:
  # Multi-user authentication (required)
  # GOOGLE_OAUTH_CLIENT_ID: your-google-oauth-client-id.apps.googleusercontent.com
  # JWT_SECRET_KEY: your-secure-jwt-secret-key  # Use Secret Manager in production
  
  # JWT configuration (optional, has defaults)
  # JWT_ALGORITHM: HS256
  # JWT_EXPIRATION_HOURS: 24
  
  # Google Calendar/Sheets integration (optional)
  # GOOGLE_CALENDAR_CREDENTIALS_PATH: path/to/credentials.json
  # GOOGLE_SHEETS_CREDENTIALS_PATH: path/to/credentials.json
  # GOOGLE_CALENDAR_ID: primary
  
  # Database (optional, defaults to SQLite)
  # DATABASE_URL: sqlite:///./qzwhatnext.db
  # For Postgres (e.g., Cloud SQL), set DATABASE_URL to a postgres URL.
  # Example (Cloud Run unix socket style):
  # DATABASE_URL: postgresql+psycopg://USER:PASSWORD@/DB_NAME?host=/cloudsql/INSTANCE_CONNECTION_NAME
  
  # AI inference (optional)
  # OPENAI_API_KEY: your-openai-api-key  # Use Secret Manager in production
  
  DEBUG: "False"

handlers:
- url: /.*
  script: auto

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

