name: Backlog item
description: Standardized feature/enhancement request
title: "Backlog: <short title>"
labels:
  - "status:triage"
body:
  - type: textarea
    id: user_value
    attributes:
      label: User value
      description: What problem does this solve? Who benefits and how?
      placeholder: |
        As a <user>, I want <capability> so that <outcome>.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (urgent)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Effort
      options:
        - S
        - M
        - L
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - low
        - medium
        - high
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Product planning status (separate from open/closed).
      options:
        - triage
        - planned
        - in_progress
        - blocked
        - done
    validations:
      required: true

  - type: checkboxes
    id: areas
    attributes:
      label: Areas
      options:
        - label: parsing
        - label: scheduling
        - label: ranking
        - label: API
        - label: UI/UX
        - label: calendar
        - label: docs
        - label: database/migrations

  - type: textarea
    id: notes
    attributes:
      label: Notes / scope
      description: Constraints, edge cases, related links, non-goals.
      placeholder: |
        - Notes:
        - Edge cases:
        - Out of scope:
    validations:
      required: false

